"""add grades table

Revision ID: 60b3a145cf5b
Revises: f5b3f2d0f8c4
Create Date: 2026-02-24 01:23:48.651439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60b3a145cf5b'
down_revision: Union[str, None] = 'f5b3f2d0f8c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_gades_submission', 'grades', type_='unique')
    op.create_unique_constraint('uq_grades_submission', 'grades', ['submission_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_grades_submission', 'grades', type_='unique')
    op.create_unique_constraint('uq_gades_submission', 'grades', ['submission_id'])
    # ### end Alembic commands ###
