"""added allow_late to assignments

Revision ID: f5b3f2d0f8c4
Revises: b6f3130d0bee
Create Date: 2026-02-10 19:30:43.319001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5b3f2d0f8c4'
down_revision: Union[str, None] = 'b6f3130d0bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('allow_late', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'allow_late')
    # ### end Alembic commands ###
